name: image_x
description: Lazy image widget for any path [Asset, Path, Url] for all image types.
version: 0.0.7
homepage: https://github.com/HazemMonir/Flutter.ImageX

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
